'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const html = fs.readFileSync(__dirname + '/../index.html', 'utf8');

assert.match(html, /活動管理/);
assert.match(html, /id="entryView"/);
assert.match(html, /id="sectionView"/);
assert.match(html, /id="platformStatus"/);
assert.doesNotMatch(html, /id="status"/);
assert.match(html, /app-router\.js/);
assert.match(html, /accounting-views\.js/);
assert.match(html, /planning-views\.js/);
assert.match(html, /rundown-core\.js/);
assert.match(html, /rundown-views\.js/);
assert.match(html, /app-views\.js/);
assert.match(html, /activity-app\.js/);
assert.doesNotMatch(html, new RegExp('<' + 'i' + 'frame\\b', 'i'));
assert.doesNotMatch(html, /class="(?:area-switch|tabs)"/);
console.log('activity-shell tests PASS');
